[versions]
# The latest Quilt versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
parchmentmc = "2022.11.27"

kotlin = "1.9.0"
kotlinx_serialization = "1.5.1"

#fabric
fabric_loader = "0.14.21"
fabric_language_kotlin = "1.10.0+kotlin.1.9.0"
# quilt
quilt_loader = "0.20.0-beta.2"

yacl = "1.7.1"
modmenu = "4.0.6"

typesafe_config = "1.4.1"

kinecraft_serialization = "1.0.1"
minotaur="2.+"

[libraries]
# common
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# fabric
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_languageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }

# quilt
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

kotlin_stdlib_jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx_serialization_core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx_serialization" }
kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }
kotlinx_serialization_hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlinx_serialization" }
typesafe_config = { module = "com.typesafe:config", version.ref = "typesafe_config" }

parchment = { module = "org.parchmentmc.data:parchment-1.19.2", version.ref = "parchmentmc" }

kinecraft_serialization = { module = "maven.modrinth:kinecraft-serialization", version.ref = "kinecraft_serialization" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.3-SNAPSHOT" }
quilt_loom = { id = "org.quiltmc.loom", version = "1.+" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_plugin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
