modLoader = "kotlinforforge"
loaderVersion = "[4,]"
license = "MIT"
[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
logoFile = "assets/${id}/icon.png"
authors = "$author"
description = "$description"
[[dependencies.$id]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.$id]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.$id]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.$id]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[${yacl_version},)"
ordering = "NONE"
side = "BOTH"
